services:
  elasticsearch:
    image: elasticsearch:7.14.2
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - cluster.name=DataEngineeringWithPython
      - node.name=OnlyNode
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - network.host=0.0.0.0
    volumes:
      - data01:/usr/share/elasticsearch/data
    networks:
      - dataeng
  kibana:
    image: kibana:7.14.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=false
      - SERVER_HOST="0"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - dataeng
  postgres:
    image: postgres:latest
    hostname: postgres
    ports:
      - 5000:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=dataengineering
    volumes:
      - data02:/var/lib/postgresql/data
    networks:
      - dataeng
  adminer:
    image: adminer:latest
    ports:
      - 8081:8080
    restart: always
    depends_on:
      - postgres
    networks:
      - dataeng      

  airflow-scheduler:
    # TODO: to be reverted to use proper registry/distro on T39132
    # image: docker.io/bitnami/airflow-scheduler:2
    image: docker.io/bitnami/airflow-scheduler:2
    environment:
      - AIRFLOW_DATABASE_NAME=dataengineering
      - AIRFLOW_DATABASE_USERNAME=admin
      - AIRFLOW_DATABASE_PASSWORD=admin
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
    volumes:
      - airflow_scheduler_data:/bitnami
    networks:
      - dataeng
  airflow-worker:
    # TODO: to be reverted to use proper registry/distro on T39132
    # image: docker.io/bitnami/airflow-worker:2
    image: docker.io/bitnami/airflow-worker:2
    environment:
      - AIRFLOW_DATABASE_NAME=dataengineering
      - AIRFLOW_DATABASE_USERNAME=admin
      - AIRFLOW_DATABASE_PASSWORD=admin
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
    volumes:
      - airflow_worker_data:/bitnami
    networks:
      - dataeng
  airflow:
    image: docker.io/bitnami/airflow:2
    environment:
      - AIRFLOW_DATABASE_NAME=dataengineering
      - AIRFLOW_DATABASE_USERNAME=admin
      - AIRFLOW_DATABASE_PASSWORD=admin
      - AIRFLOW_EXECUTOR=CeleryExecutor
    ports:
      - '8080:8080'
    volumes:
      - airflow_data:/bitnami
    networks:
      - dataeng

volumes:
  data01:
    driver: local
  data02:
    driver: local
  airflow_scheduler_data:
    driver: local
  airflow_worker_data:
    driver: local
  airflow_data:
    driver: local

networks:
  dataeng:
    driver: bridge

